### ISSUE TITLE
Devices and OS Wrong information being printed

### ISSUE THREAD

**Issue by Mamik153** [erossini/BlazorBrowserDetect#1]
Hello,
I recently tried to use your implementation and found some issues. I will list them:

1. IsMobile, IsTablet, IsDesktop is not working perfectly - IsTablet always returns false and in tablet IsMobile returns true
2. Also Wrong OS Information for iPad.
Below image is from iPad 9th Gen:
![image](https://user-images.githubusercontent.com/30488855/162557658-4e731e06-4290-4cd8-b9df-db30de02079a.png)

4. Device type returns blank in desktop mode
![image](https://user-images.githubusercontent.com/30488855/162557713-ae353c6d-97ed-4b44-8e22-91eccf2191d7.png)

This is what I noticed after 10mins... Hope you fix them :)

**Comment by erossini** [comment]
Hi,
the browser detect is not perfect because based on the User Agent. In the recent years most of the [browser started to remove info for it](https://www.puresourcecode.com/dotnet/blazor/browser-detect-component-for-blazor/). So, there is other way to try to detect the browser and the device but definitely it is not perfect.

Not all devices allow to detect the type, vendor or model. For this reason, I use some JavaScript to detect as much details as possible but again it is not perfect.

To detect if a device is an iPad, I check the screen size. Happy to check better the list. Could you provide me more info about your device(s)?

For more reference, please read my post [here](https://www.puresourcecode.com/dotnet/blazor/browser-detect-component-for-blazor/).

Thank you in advance,
Enrico

**Comment by Mamik153** [comment]
Hey,
I read your post and yes it does seem to be an issue using User-Agent. I have been using iPad Mini, iPhone 11, OnePlus Nord & Asus ROG laptop for testing FYI and that's when I noticed these issues that I raised.

PS., I actually moved around to using a custom solution using device width to make things work the way I wanted to.
